export interface AITool {
  id: string;
  name: string;
  category: string;
  shortDesc: string;
  fullDesc: string;
  tags: string[];
  pricing: 'free' | 'premium';
  rating: number;
  reviews: number;
  usageCount: number;
  icon: string; // lucide icon name
  createdAt: string;
}

export const categories = [
  { id: 'writing', label: 'Writing', desc: 'Generate, edit, and refine text content at scale.', color: 'from-violet-400 to-fuchsia-400' },
  { id: 'images', label: 'Images', desc: 'Create, edit, and enhance visual assets instantly.', color: 'from-amber-300 to-orange-300' },
  { id: 'video', label: 'Video', desc: 'Generate clips, edit timelines, and produce media.', color: 'from-rose-300 to-red-300' },
  { id: 'audio', label: 'Audio', desc: 'Synthesize voice, music, and sound design.', color: 'from-emerald-300 to-teal-300' },
  { id: 'coding', label: 'Coding', desc: 'Write, review, and debug software with AI.', color: 'from-cyan-400 to-blue-400' },
  { id: 'pdf', label: 'PDF', desc: 'Parse, summarize, and generate document outputs.', color: 'from-indigo-300 to-purple-300' },
  { id: 'business', label: 'Business', desc: 'Analyze data, draft reports, and automate workflows.', color: 'from-sky-300 to-blue-300' },
  { id: 'marketing', label: 'Marketing', desc: 'Create campaigns, copy, and creative assets.', color: 'from-pink-300 to-rose-300' },
  { id: 'seo', label: 'SEO', desc: 'Optimize content, keywords, and ranking strategies.', color: 'from-lime-300 to-green-300' },
  { id: 'education', label: 'Education', desc: 'Build courses, quizzes, and learning materials.', color: 'from-amber-200 to-yellow-300' },
  { id: 'productivity', label: 'Productivity', desc: 'Automate tasks, manage projects, and streamline work.', color: 'from-slate-300 to-gray-400' },
  { id: 'prompt-engineering', label: 'Prompt Engineering', desc: 'Design, test, and optimize AI prompts.', color: 'from-gold to-copper' },
];

export const tools: AITool[] = [
  {
    id: 'draft-01',
    name: 'AlphaWrite Draft',
    category: 'writing',
    shortDesc: 'Generate long-form articles with citations.',
    fullDesc: 'AlphaWrite Draft produces structured long-form content with in-text citations, outline generation, and tone adaptation. Supports research-backed synthesis for enterprise reports, blog posts, and whitepapers.',
    tags: ['long-form', 'citations', 'tone'],
    pricing: 'free',
    rating: 4.8,
    reviews: 342,
    usageCount: 12842,
    icon: 'PenTool',
    createdAt: '2024-02-01',
  },
  {
    id: 'draft-02',
    name: 'AlphaEdit Pro',
    category: 'writing',
    shortDesc: 'Professional editing with grammar and style checks.',
    fullDesc: 'AlphaEdit Pro runs multi-pass grammar, clarity, and style analysis against enterprise style guides. Includes plagiarism detection and tone-matching for brand consistency.',
    tags: ['editing', 'grammar', 'style'],
    pricing: 'premium',
    rating: 4.9,
    reviews: 511,
    usageCount: 22100,
    icon: 'Edit3',
    createdAt: '2024-03-10',
  },
  {
    id: 'img-01',
    name: 'AlphaImage Gen',
    category: 'images',
    shortDesc: 'Generate high-fidelity images from text.',
    fullDesc: 'Produce photorealistic, illustration, and concept art from detailed text prompts. Supports negative prompting, aspect-ratio control, and batch generation.',
    tags: ['generation', 'batch', 'photoreal'],
    pricing: 'free',
    rating: 4.7,
    reviews: 893,
    usageCount: 45200,
    icon: 'Image',
    createdAt: '2024-01-15',
  },
  {
    id: 'img-02',
    name: 'AlphaUpScale',
    category: 'images',
    shortDesc: 'Upscale images with detail preservation.',
    fullDesc: 'Enhance resolution up to 4K while preserving textures, edges, and fine detail. Works with photographs, illustrations, and text-in-image elements.',
    tags: ['upscale', 'enhance', '4k'],
    pricing: 'premium',
    rating: 4.6,
    reviews: 312,
    usageCount: 18700,
    icon: 'ZoomIn',
    createdAt: '2024-04-05',
  },
  {
    id: 'vid-01',
    name: 'AlphaClip Maker',
    category: 'video',
    shortDesc: 'Generate short video clips from prompts.',
    fullDesc: 'Create 3-10 second video segments with motion, lighting, and scene coherence. Supports style prompts and character consistency across clips.',
    tags: ['generation', 'short-form', 'motion'],
    pricing: 'free',
    rating: 4.5,
    reviews: 210,
    usageCount: 9400,
    icon: 'Video',
    createdAt: '2024-05-20',
  },
  {
    id: 'aud-01',
    name: 'AlphaVoice',
    category: 'audio',
    shortDesc: 'Text-to-speech with emotional tone.',
    fullDesc: 'Convert text to lifelike voice with emotional inflection, pacing control, and multi-language support. Includes voice cloning for brand consistency.',
    tags: ['tts', 'voice', 'multilingual'],
    pricing: 'premium',
    rating: 4.8,
    reviews: 402,
    usageCount: 15300,
    icon: 'Mic',
    createdAt: '2024-03-22',
  },
  {
    id: 'code-01',
    name: 'AlphaCode Assist',
    category: 'coding',
    shortDesc: 'Write and review code in any language.',
    fullDesc: 'Generate functions, classes, and full modules with documentation. Includes code review, security audit suggestions, and test-case generation.',
    tags: ['generation', 'review', 'tests'],
    pricing: 'free',
    rating: 4.9,
    reviews: 1204,
    usageCount: 67800,
    icon: 'Code2',
    createdAt: '2024-01-05',
  },
  {
    id: 'code-02',
    name: 'AlphaDebug Pro',
    category: 'coding',
    shortDesc: 'Identify bugs and suggest fixes.',
    fullDesc: 'Analyze stack traces, logs, and source files to identify root causes and provide patched solutions with explanations.',
    tags: ['debug', 'fix', 'explain'],
    pricing: 'premium',
    rating: 4.7,
    reviews: 670,
    usageCount: 32400,
    icon: 'Bug',
    createdAt: '2024-06-01',
  },
  {
    id: 'pdf-01',
    name: 'AlphaPDF Reader',
    category: 'pdf',
    shortDesc: 'Extract and summarize PDFs.',
    fullDesc: 'Parse complex PDFs including tables, forms, and scanned pages. Generates summaries, answers questions, and extracts structured data.',
    tags: ['parse', 'summarize', 'extract'],
    pricing: 'free',
    rating: 4.6,
    reviews: 288,
    usageCount: 14200,
    icon: 'FileText',
    createdAt: '2024-02-18',
  },
  {
    id: 'biz-01',
    name: 'AlphaData Analyst',
    category: 'business',
    shortDesc: 'Analyze spreadsheets and generate insights.',
    fullDesc: 'Process CSV, Excel, and database outputs to produce charts, trend analysis, and executive summaries with statistical significance.',
    tags: ['analysis', 'charts', 'trends'],
    pricing: 'premium',
    rating: 4.8,
    reviews: 445,
    usageCount: 21100,
    icon: 'BarChart3',
    createdAt: '2024-04-12',
  },
  {
    id: 'mkt-01',
    name: 'AlphaCampaign',
    category: 'marketing',
    shortDesc: 'Generate marketing copy and campaigns.',
    fullDesc: 'Create email sequences, landing page copy, social posts, and ad creatives aligned to brand voice and audience segments.',
    tags: ['copy', 'campaign', 'social'],
    pricing: 'free',
    rating: 4.4,
    reviews: 156,
    usageCount: 8300,
    icon: 'Megaphone',
    createdAt: '2024-03-30',
  },
  {
    id: 'seo-01',
    name: 'AlphaSEO Scout',
    category: 'seo',
    shortDesc: 'Optimize content for search engines.',
    fullDesc: 'Analyze keywords, suggest meta structures, generate optimized headings, and provide internal linking recommendations.',
    tags: ['keywords', 'meta', 'optimize'],
    pricing: 'free',
    rating: 4.5,
    reviews: 290,
    usageCount: 16700,
    icon: 'Search',
    createdAt: '2024-05-10',
  },
  {
    id: 'edu-01',
    name: 'AlphaLearn Builder',
    category: 'education',
    shortDesc: 'Design courses, quizzes, and learning paths.',
    fullDesc: 'Generate structured lessons with assessments, interactive exercises, and progress tracking. Supports multiple learning formats.',
    tags: ['courses', 'quizzes', 'paths'],
    pricing: 'premium',
    rating: 4.7,
    reviews: 380,
    usageCount: 19800,
    icon: 'GraduationCap',
    createdAt: '2024-06-15',
  },
  {
    id: 'prod-01',
    name: 'AlphaTask Flow',
    category: 'productivity',
    shortDesc: 'Automate repetitive work tasks.',
    fullDesc: 'Create automated workflows for email sorting, document filing, meeting summaries, and notification management.',
    tags: ['automation', 'workflows', 'tasks'],
    pricing: 'free',
    rating: 4.6,
    reviews: 410,
    usageCount: 25600,
    icon: 'Workflow',
    createdAt: '2024-01-25',
  },
  {
    id: 'pe-01',
    name: 'AlphaPrompt Lab',
    category: 'prompt-engineering',
    shortDesc: 'Design, test, and refine AI prompts.',
    fullDesc: 'Build prompt libraries with A/B testing, version control, and performance tracking. Includes template generation for common tasks.',
    tags: ['library', 'testing', 'templates'],
    pricing: 'premium',
    rating: 4.9,
    reviews: 620,
    usageCount: 31200,
    icon: 'Lightbulb',
    createdAt: '2024-02-28',
  },
];
